apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-helloworld-aks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-helloworld-aks
  template:
    metadata:
      labels:
        app: springboot-helloworld-aks
    spec:
      containers:
        - name: springboot-helloworld-aks
          image: kubeclusterregistry1.azurecr.io/image-workflow-1691378860661:0b996f41c665d9006043bb4eab360aeb4b97eb63
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-helloworld-aks
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springboot-helloworld-aks