name: Build a Docker image and Push it to ACR
kind: Pod
apiversion: v1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/Dockerfile-login@v1
        with:
          login-server: kubeclusterregistry1.azurecr.io
          username: kubeclusterregistry1
          password: hIVOXGQzqTQutrQRtvSXXTmiLfDMTxfNOEH5OgBwtr+ACRC1nqJv
      - run: |
          docker build . -t kubeclusterregistry1.azurecr.io/image-workflow-1691378860661:${{ github.sha }}
          docker push kubeclusterregistry1.azurecr.io/image-workflow-1691378860661:${{ github.sha }}