name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/Dockerfile-login@v1
        with:
          login-server: arvcontainerregistry1.azurecr.io
          username: arvcontainerregistry1
          password: aRHJnpnAY6SQCVJBiSjOLfNrrqSZ30tE47cT6zR1Pb+ACRC5VwAp
      - run: |
          docker build . -t arvcontainerregistry1.azurecr.io/appkube:${{ github.sha }}
          docker push arvcontainerregistry1.azurecr.io/appkube:${{ github.sha }}